### PR TITLE
Request 2019.01.02 tag on 2019.01 branch, FMS2020.02 diag_axis_init  interface changes

### PR DESCRIPTION
**Pull request by nikizadehgfdl**
**Description**
- The public interface diag_axis_init has changed in 2020.02 (fms2 work).
  One optional argument is added. However this optional argument is required
  for the  "corner" diagnostics to work.
- MOM6/SIS2 developers requsted an interim FMS "release" with just this interface
  change so that they can use it to make changes to their dev/gfdl branch that
  uses the new interface without actually using fms2 diag_manager.
  This update is an attempt to address that request.

Fixes # (issue)
#435 
Please tag this as 2019.01.02 on the 2019.01 branch

**How Has This Been Tested?**
Passed regression tests for ocean-ice and ESM4.

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Comment by nikizadehgfdl** [comment]
@marshallward , @adcroft  could you take a look at this to see if it satisfies the MOM6/SIS2 requirements for changing the diag_axis public interface.

**Comment by marshallward** [comment]
I haven't been following this issue enough, but if it resolves the I/O transition then it looks good to me.

**Comment by adcroft** [comment]
I've tested that MOM6 builds with this version of FMS although I have not tested the new optional argument.

**Comment by adcroft** [comment]
Any idea of a time-line on this?

**Comment by thomas-robinson** [comment]
@nikizadehgfdl this isn't passing the check, and I think it's because you don't have travis activated for your fork/github account.  It appears that when you try to merge to a branch, travis requires runs on here and in your own fork.

**Comment by nikizadehgfdl** [comment]
I do have Travis for my github account, but for whatever reason it's not activated on my FMS fork like it is on my MOM6 fork.

**Comment by thomas-robinson** [comment]
@adcroft This is merged in now and tagged at 2019.01.02

**Comment by adcroft** [comment]
Great - thanks.

**Pull request merged**
