### PR TITLE
Adds fms2io's version of get_mosaic_tile_grid

### LINKED ISSUE #501: FMS2: Need an equivalent to the fms subroutine get_mosaic_tile_grid
**Is your feature request related to a problem? Please describe.**
I am in the process of replacing use of old io in FV3 to the new fms2 io and the file [fv_grid_tools.F90](https://github.com/laurenchilutti/GFDL_atmos_cubed_sphere/blob/fms2io_part2/tools/fv_grid_tools.F90#L131) uses [get_mosaic_tile_grid](https://github.com/NOAA-GFDL/FMS/blob/master/fms/fms_io.F90#L7866).  I do not see an equivalent or comparable function for this in fms2.

**Describe the solution you'd like**
Create a function comparable to ```get_mosaic_tile_grid``` in fms2.

**Describe alternatives you've considered**
Only alternative would be to continue using the old io.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by uramirez8707**
**Description**
This PR just adds fms2io's version of get_mosaic_tile_grid. 

Fixes #501 

**How Has This Been Tested?**
Please describe the tests that you ran to verify your changes. Please also note
any relevant details for your test configuration (e.g. compiler, OS).  Include
enough information so someone can reproduce your tests.

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Comment by uramirez8707** [comment]
@laurenchilutti 
Please test. All you *should* need to do is replace
`use fms_mod,           only: get_mosaic_tile_grid` 

with 
`use fms2_io_mod,           only: get_mosaic_tile_grid`

But let me know if you run into any problems.

**Comment by thomas-robinson** [comment]
Why can't you just use this from fms_mod?  Is it removed?

**Comment by laurenchilutti** [comment]
When discussing the update to fms2 in the GFDL_atmos_cubed_sphere repository, I was told that we hoped to completely replace fms with fms2.  If this is not the case, then I could still use the fms_mod.

**Comment by laurenchilutti** [comment]
@uramirez8707 I have tested and it works in my case. Thanks!

**Pull request merged**
