### PR TITLE
Added additional checks to prevent time_bnds from being overwritten

### LINKED ISSUE #463: diag_manager overwrites time_bnds for each variable that was register
**Describe the bug**
After diag-manager_end is called: 

1. It loops through the number of files and calls `closing_file`: 
https://github.com/NOAA-GFDL/FMS/blob/37a607ae03ee9e05d4404606e602f5a6796e5339/diag_manager/diag_manager.F90#L3697-L3699
2. In `closing_file` it loops through the num_fields and calls `writing_field`
https://github.com/NOAA-GFDL/FMS/blob/37a607ae03ee9e05d4404606e602f5a6796e5339/diag_manager/diag_manager.F90#L3727
...
https://github.com/NOAA-GFDL/FMS/blob/37a607ae03ee9e05d4404606e602f5a6796e5339/diag_manager/diag_manager.F90#L3760
3. In `writing_field`, `diag_data_out` is called
https://github.com/NOAA-GFDL/FMS/blob/37a607ae03ee9e05d4404606e602f5a6796e5339/diag_manager/diag_manager.F90#L3535
4. In `diag_data_out`, it loops through the num_fields **AGAIN** and it writes out the time_bnds, if`num == field`
https://github.com/NOAA-GFDL/FMS/blob/37a607ae03ee9e05d4404606e602f5a6796e5339/diag_manager/diag_util.F90#L2555-L2581

This means that time_bnds is going to be rewritten for every field because of the **FIRST**  loop through the num_fields in step 2 and the values for the last variables in `num_field` will win :) 
It looks like the same thing is happening with `Time` as well...

This may cause the problem in issue #448 if the last field was registered but data was never sent since `start_dif` will be set to the initial model time. 

**To Reproduce**
Run the awg_xml in 448. Time_bnds is wrong because send_data is never called on the last variable that gets registered (the last variable in the loop in step 2). 

I was able to reproduce the issue using the diag_table and input_nml in `/lustre/f2/scratch/gfdl/Uriel.Ramirez/work/c96L33_am4p0_1x12m0d_432x1a.o268649219`
where I only write 1 history file with two variables for two days. 

**Expected behavior**
`Time_bnds` should be written correctly and maybe only once?

**System Environment**
Describe the system environment, include:
This occurs in any system. 

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by rem1776**
**Description**
Added additional checks of dif values to prevent incorrect duplicate writes on time_bnds
Fixes #463 

**How Has This Been Tested?**
Tested through Travis CI

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Comment by uramirez8707** [comment]
@thomas-robinson @rem1776 

This does not work because: 
Before `diag_data_out` is called, `middle_time` is defined using the `last_output` and `next_output`:
https://github.com/NOAA-GFDL/FMS/blob/764513e8b847c5d687925376e2f47d9cfda9b956/diag_manager/diag_manager.F90#L3531

This `middle_time` is an input to the `diag_data_out` call, which is used to defined `diff`. So the if statement that was added will always be true. 

One way to fix this, is to use `files(file)%rtime_current` instead of `diff` which is set to the correct time. This works for me ...

**Comment by colingladueNOAA** [comment]
@rem1776  Hey how did you defeat travis?!

**Comment by thomas-robinson** [comment]
@uramirez8707 did you test this with the case you had set up?

**Comment by uramirez8707** [comment]
@thomas-robinson Sorry forgot to update the PR

I tested this with the unit test I had set up and I also ran a year run of AM4-c96L33_am4p0 experiment and I now get the correct time_bnds.

**Comment by rem1776** [comment]
Made a new PR for this since I messed up the branch and it got deleted  
It's now in #512

**Pull request merged**
