### PR TITLE
fms2_io and diag_manager updates

### PR DESCRIPTION
**Pull request by thomas-robinson**
@wrongkindofdoctor This branch should be made the head of the development stream for fms2_io

### CODE REVIEW

**Comment by thomas-robinson** [comment]
@underwoo what version of mpif90 is the travisCI using?  The error I see is:
```
      type is (character(len=*))
                                1
Error: Associate-name '__tmp_CHARACTER_0_1' at (1) is used as array
```
This may have failed due to a [gfortran bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55901)

**Comment by underwoo** [comment]
@thomas-robinson, from the [travis-CI log](https://travis-ci.org/NOAA-GFDL/FMS/builds/567974582?utm_source=github_status&utm_medium=notification) it appears to be using the OpenMPI version 1.6.5.

**Comment by thomas-robinson** [comment]
@underwoo Well then the CI failed because of a compiler bug in an old compiler.

**Comment by wrongkindofdoctor** [comment]
@underwoo @thomas-robinson The docker image used for the travis-ci environment needs to be updated to support a newer version of gnu. I have tested the new FMS-io in the MOM6-solo configuration on gaea with gcc 5.3 and gcc 7.3 in debug, prod, and repro without issue, and suggest using a configuration that supports v 7.3 if it is available.

**Comment by underwoo** [comment]
Please take some time, and feel free to pull in Uriel, to update the `.travis.yml` to use a newer Ubuntu image.  Look at https://docs.travis-ci.com/user/reference/overview/ for more information.  I believe the Bionic Beaver version of Ubuntu (18.04) has a new enough gcc.

**Comment by thomas-robinson** [comment]
I opened #105 and assigned it to me.  Thanks for the info @underwoo .  I just needed a point in the right direction.

**Comment by marshallward** [comment]
For what it's worth, I just tested this with PGI 15.3 and got a somewhat similar error:
```
PGF90-S-0000-Internal compiler error. size_of: attempt to get size of assumed size character       0 (../src/fms2_io/include/get_data_type_string.inc: 48)
  0 inform,   0 warnings,   1 severes, 0 fatal for get_data_type_string_1d
PGF90-S-0000-Internal compiler error. size_of: attempt to get size of assumed size character       0 (../src/fms2_io/include/get_data_type_string.inc: 72)
  0 inform,   0 warnings,   1 severes, 0 fatal for get_data_type_string_2d
PGF90-S-0000-Internal compiler error. size_of: attempt to get size of assumed size character       0 (../src/fms2_io/include/get_data_type_string.inc: 96)
  0 inform,   0 warnings,   1 severes, 0 fatal for get_data_type_string_3d
PGF90-S-0000-Internal compiler error. size_of: attempt to get size of assumed size character       0 (../src/fms2_io/include/get_data_type_string.inc: 120)
  0 inform,   0 warnings,   1 severes, 0 fatal for get_data_type_string_4d
PGF90-S-0000-Internal compiler error. size_of: attempt to get size of assumed size character       0 (../src/fms2_io/include/get_data_type_string.inc: 144)
  0 inform,   0 warnings,   1 severes, 0 fatal for get_data_type_string_5d
````
Not the same file, but a similar `select type` block containing a character switch.

I was also able to reproduce the original error using GNU 4.9 on the workstations.  Intel 15 worked without error, though I did not test in runtime.

**Comment by marshallward** [comment]
Sorry, slight amendment.  The include directory said PGI 15.3, but the compiler version was 16.5.

**Comment by marshallward** [comment]
Just testing PGI 18.7, and it seems to have gotten past those blocks, so probably something manageable.  Just something to keep in mind for internal testing, I suppose.

The select type blocks do seem a volatile though, and may be an issue for outside users, so might be worth finding a plan for when they are not working.

**Comment by thomas-robinson** [comment]
I submitted #106 which resolves #105 describing this compiler issue.  @wrongkindofdoctor Once #106 is merged in, we can rerun the CI to see if it works.

**Comment by wrongkindofdoctor** [comment]
@thomas-robinson I've modified the pull request to point to the new fms-io-dev branch that is currently aligned with master. It looks like all you have to do is resolve the conflicts in the .gitignore file and the 2 test_fms files.

**Comment by wrongkindofdoctor** [comment]
Closing this pull request. #108  addresses the conflicts.

**Pull request closed without merging**
