### PR TITLE
chore: update libFMS module with new routines

### PR DESCRIPTION
**Pull request by rem1776**
**Description**
Just adds a the past few updates to the libFMS.F90 file so that they're accessible through the module. If anything else added was public and not included here please let me know

**How Has This Been Tested?**
intel/impi 2020 on amd

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Review by bensonr — COMMENTED** [review]
Are any or all of these intended for more than internal FMS use?

**Comment by rem1776** [comment]
> Are any or all of these intended for more than internal FMS use?

I know the mpp_shift_nest_domains is for external use and some of the string routines are as well I believe. Not too sure about the parser routines, but they're public in their module so they'd be accessible either way.

**Comment by bensonr** [comment]
@rem1776  - My comment was specific to the yaml and string routines/functions.  It's public in our modules because we need to use them throughout FMS itself, but that doesn't mean we necessarily want to expose them as externals from FMS by default.

**Comment by rem1776** [comment]
@bensonr Yeah I get what you mean, I think we would want these included here in this case. I spoke to Uriel since he wrote most of the routines and he thinks they should be accessible externally for models.

**Review by bensonr — APPROVED** [review]

**Pull request merged**
