### PR TITLE
Mixed mode updates for beta1

### PR DESCRIPTION
**Pull request by rem1776**
**Description**
Merges in the latest batch of mixed precision updates, includes:
- amip_interp
- column_diagnostics
- mosiac/mosaic2
- tridiagonal

Also adds unit tests for the existing updates to coupler and topography

**How Has This Been Tested?**
amd box with latest oneapi

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Review by thomas-robinson — DISMISSED** [review]
I am trusting the team did a good/thorough review here

**Review by bensonr — COMMENTED** [review]
Is mosaic deprecated in favor of mosaic2?  If so, I find it confusing that we have a _test_fms/mosaic_ directory, but it contains tests for mosaic2.  I think it should be renamed to _test_fms/mosaic2_

**Comment by mlee03** [comment]
@rem1776 PR to your branch with mosaic changes coming soon

**Review by thomas-robinson — APPROVED** [review]

**Review by bensonr — APPROVED** [review]
Will FMS/mosaic be going away at some point?

**Comment by mlee03** [comment]
@bensonr it will with mosaic cleanup

**Pull request merged**
