### PR TITLE
Adds initialization call to atmosphere io test to prevent it from fai…

### LINKED ISSUE #495: test_fms/fms2_io/test_atmosphere_io fails when run...
There is a test, currently skipped, which, when I run, fails like this:

```
(base) ed@mikado:~/f4/test_fms/fms2_io$ bash -x ./test_atmosphere_io.sh
+ . ../test_common.sh
++ set -e
++ TEST_PASS=0
++ TEST_FAIL=1
++ TEST_SKIP=77
++ TEST_ERROR=99
++ top_srcdir=/home/ed/f4
++ top_buildir=/home/ed/f4
++ mpi_launcher=mpirun
++ oversubscribe=
+ printf 'EOF\n&dummy\nEOF'
+ cat
+ run_test test_atmosphere_io 6
+ test x = xskip
+ test xmpirun '!=' x
+ npes='-n 6'
+ mpirun -n 6 ./test_atmosphere_io
 Using            6  MPI ranks.
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
NOTE from PE     0: MPP_DOMAINS_SET_STACK_SIZE: stack size set to    32768.
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
 Cubed-sphere domain decomposition
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96
 Cubed-sphere domain decomposition
whalo =    2, ehalo =    2, shalo =    2, nhalo =    2
  X-AXIS =   96
  Y-AXIS =   96

FATAL from PE     0: netcdf_file_open:: fms2_ncchksz not set.


FATAL from PE     2: netcdf_file_open:: fms2_ncchksz not set.


FATAL from PE     4: netcdf_file_open:: fms2_ncchksz not set.


FATAL from PE     5: netcdf_file_open:: fms2_ncchksz not set.


FATAL from PE     0: netcdf_file_open:: fms2_ncchksz not set.


FATAL from PE     1: netcdf_file_open:: fms2_ncchksz not set.


FATAL from PE     3: netcdf_file_open:: fms2_ncchksz not set.

#0  0x7fb508cfacd1 in ???
#0  0x7f4d98792cd1 in ???
#1  0x56111b901cd5 in __mpp_mod_MOD_mpp_error_basic
	at ../mpp/include/mpp_util_mpi.inc:70
#1  0x55dc69635cd5 in __mpp_mod_MOD_mpp_error_basic
	at ../mpp/include/mpp_util_mpi.inc:70
#0  0x7fc75a548cd1 in ???
#2  0x56111bc276c5 in __fms_io_utils_mod_MOD_error
	at /home/ed/f4/fms2_io/fms_io_utils.F90:164
#2  0x55dc6995b6c5 in __fms_io_utils_mod_MOD_error
	at /home/ed/f4/fms2_io/fms_io_utils.F90:164
#3  0x56111bc583df in __netcdf_io_mod_MOD_netcdf_file_open
	at /home/ed/f4/fms2_io/netcdf_io.F90:499
#3  0x55dc6998c3df in __netcdf_io_mod_MOD_netcdf_file_open
	at /home/ed/f4/fms2_io/netcdf_io.F90:499
#4  0x56111bc8422a in __fms_netcdf_domain_io_mod_MOD_open_domain_file
	at /home/ed/f4/fms2_io/fms_netcdf_domain_io.F90:379
#4  0x55dc699b822a in __fms_netcdf_domain_io_mod_MOD_open_domain_file
	at /home/ed/f4/fms2_io/fms_netcdf_domain_io.F90:379
#5  0x56111b8736ae in test_atmosphere_io
	at /home/ed/f4/test_fms/fms2_io/test_atmosphere_io.F90:113
#6  0x56111b87cb08 in main
	at /home/ed/f4/test_fms/fms2_io/test_atmosphere_io.F90:22
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 2
#5  0x55dc695a76ae in test_atmosphere_io
	at /home/ed/f4/test_fms/fms2_io/test_atmosphere_io.F90:113
#6  0x55dc695b0b08 in main
	at /home/ed/f4/test_fms/fms2_io/test_atmosphere_io.F90:22
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
```

This seems to be an initialization problem.

The "skip" option in your testing has allowed a lot of programmers to check in a lot of broken tests, and then skip them. This is the worst of all worlds - you are paying someone to write test code, but not getting any value out of that code, because you are skipping it. Also, your product is still untested. 

So let's get this test working, and start getting some value out of it.

### PR DESCRIPTION
**Pull request by rem1776**
**Description**
Adds an initialization call in order to prevent the atmosphere io test from failing, but this causes another test (test_fms2_io) to fail instead

Fixes #495
**How Has This Been Tested?**
On travis and skylake with the intel compiler, the call to fms_init_io fixes the atmosphere test, but causes test_fms2_io to fail.

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [ ] `make distcheck` passes

### CODE REVIEW

**Comment by uramirez8707** [comment]
@rem1776 I **think** I know what is going on here. 

This is running a `make -j distcheck`. The `j` means that is it running in parallel with how ever many cores are available. So all the job scripts `*.sh` might try to run at the same time. 

Both the test in `test_atmosphere_io.F90` and `test_fms2_io.F90` try to create a restart file `"atmosphere.nc",`(same filename but different variables) and read it back, and compare the data written with the data read. 

https://github.com/NOAA-GFDL/FMS/blob/368dfb7916d80f32fb4317d17bb0f547115f53ab/test_fms/fms2_io/test_atmosphere_io.F90#L112

----
https://github.com/NOAA-GFDL/FMS/blob/368dfb7916d80f32fb4317d17bb0f547115f53ab/test_fms/fms2_io/atmosphere_restart_file_test.inc#L92 which is called in https://github.com/NOAA-GFDL/FMS/blob/368dfb7916d80f32fb4317d17bb0f547115f53ab/test_fms/fms2_io/test_fms2_io.F90#L157

Because the tests **may** be running in parallel so they may interfere with each other. For example, `test_fms2_io` **may** be trying to read the "atmosphere.nc" file created by test_atmosphere_io.F90, which will be different. 

I see two ways of fixing this: 
1. Run the `test_atmosphere_io` test in the same job script as `test_fms2_io`, (see https://github.com/NOAA-GFDL/FMS/commit/69d9bf378a4e7e55df0daeafe628db152d7539d0). This way the test are going to run one after the other instead of in parallel (probably not desirable)
2. I haven't tested this, but I *think*, if you rename the file that one of tests writes then it should work.
so replace 
https://github.com/NOAA-GFDL/FMS/blob/368dfb7916d80f32fb4317d17bb0f547115f53ab/test_fms/fms2_io/test_atmosphere_io.F90#L112

with something like
```F90
call open_check(open_file(fileobj, "test_atmosphere_io.nc", "overwrite", &
```

**Comment by rem1776** [comment]
@uramirez8707 thanks for the help, I tried to rename the file but it looks like it's still failing from an invalid pointer. The same name for the restart file is also used in atmosphere_restart_file_test.inc but that shouldn't affect it with the name change. I'll try to see if something isn't initialized for the test

**Comment by rem1776** [comment]
This seems to be failing because of the checksum values when read_restart is called. Could the file name change cause this?

https://github.com/NOAA-GFDL/FMS/blob/73b62f1d6228c8056caeaada3bf79f661e254147/test_fms/fms2_io/test_atmosphere_io.F90#L485

**Comment by uramirez8707** [comment]
@rem1776 Passing this test requires a code change. I am currently testing a fix.

**Comment by rem1776** [comment]
Closing since this is included in #542

**Pull request closed without merging**
