### PR TITLE
Diag manager[2] fix when history files written out periodically

### LINKED ISSUE #636: redundancy in data output for history files written out periodically
**Describe the bug**
For diagnostic files written out periodically during a run, data set corresponding to all the previous time_bounds gets written out to each output file. 

For example, given the following diag_table specification 

``"ocn%4yr%2mo%2dy%2hr",      6,  "hours", 1, "hours", "time", 6, "hours", "1901 1 1 0 0 0"``
 
the file ``ocn_2016_10_03_09.nc`` contains the data set already printed in ``ocn_2016_10_03_03.nc``

**To Reproduce**
The ``test_diag_manager_time`` unit test in ``diag_manager`` reproduces this problem.

**Expected behavior**
Data corresponding to the current time_bound should only be written out to its corresponding file.

**System Environment**
This behavior will occur on all systems.

**Additional context**
The UFS models require this fix in order to use fms2_io.

### PR DESCRIPTION
**Pull request by uramirez8707**
**Description**
Resets the length of the time dimension back to zero when opening a new file in diag_manager when history files written out periodically.

Fixes #636 

**How Has This Been Tested?**
`make check` passes on skylake with intel 

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Comment by thomas-robinson** [comment]
@uramirez can you test this with at least AM4.  I think c96L33_am4p0_cmip6Diag run for a month or a year would be good.  You should also make sure the restart runs work.

**Comment by mlee03** [comment]
I'll test with the UFS models, and as @uramirez suggested, with fms2_io and mpp_io :D

**Comment by uramirez8707** [comment]
I ran c96L33_am4p0_cmip6Diag in orion with intel20, prod-openmp for `<run months="2">` and `<run months="1 1">` 

FMS-2020.04 reproduces FMS-master+this fix :)

**Review by thomas-robinson — APPROVED** [review]
This should be tested by all models to see if it changes history files, especially during a restart run.

**Comment by thomas-robinson** [comment]
@rem1776 You need to create a release/2020.04 branch so this can be merged into there.  I made it a draft until the branch is created and the branch destination is changed.

We should run testing on all of the models to ensure this doesn't change anything in the history files.  This could be included in the 20201.01-alpha1 tag if you want.

**Comment by uramirez8707** [comment]
@rem1776 Don't merge this yet. 

I think there is still something wrong with the ufs model.

**Review by rem1776 — APPROVED** [review]

**Comment by mlee03** [comment]
All UFS regression tests passed!

**Review by mlee03 — APPROVED** [review]

**Pull request merged**
