### PR TITLE
Fix test_fms/mpp makefile.am

### PR DESCRIPTION
**Pull request by wrongkindofdoctor**
**Description**
This PR is (trying) to fix issues in the test_fms/mpp Makefile.am caused by merging PR [#651](https://github.com/NOAA-GFDL/FMS/pull/651) that did not update the accessory modules created in PR [#676](https://github.com/NOAA-GFDL/FMS/pull/676).

Fixes # (issue)

**How Has This Been Tested?**

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Comment by underwoo** [comment]
@wrongkindofdoctor it was brought to my attention that something in #651 may have caused issues, in particular with this PR.  I've looked over your modifications, but I cannot figure out what it is you are trying to fix.  Could you please open an issue explaining what the problem is and then link this PR with that issue.

**Comment by wrongkindofdoctor** [comment]
Thanks @underwoo . I've been trying to figure out the right configuration based on your updates, but will probably have to call it in for today since this still doesn't link the mpp accessory module files here or on the AMD box.

**Comment by underwoo** [comment]
> Thanks @underwoo . I've been trying to figure out the right configuration based on your updates, but will probably have to call it in for today since this still doesn't link the mpp accessory module files here or on the AMD box.

Give me your ebb config and I'll see what might be going on.

**Comment by wrongkindofdoctor** [comment]
@underwoo  You'll need to define ebb for me (google was no help)?

Regardless, my autotools setup file on the AMD box is /home/Jessica.Liptak/autotools_env_intel_impi
workflow:
```
> cd FMS
> source /home/Jessica.Liptak/autotools_env_intel_impi
> autoreconf -fi
> cd build_intel
> make distclean
> ../configure
> make check -k
```
Error message for test_mpp shows `cp: cannot stat '../../.mods/compare_data_checksums.mod': No such file or directory`, and similarly for the other accessory .mod files:
```
Making check in mpp
make[2]: Entering directory '/home/Jessica.Liptak/FMS/build_intel/test_fms/mpp'
mpiifort -DPACKAGE_NAME=\"GFDL\ FMS\ Library\" -DPACKAGE_TARNAME=\"FMS\" -DPACKAGE_VERSION=\"2020.04\" -DPACKAGE_STRING=\"GFDL\ FMS\ Library\ 2020.04\" -DPACKAGE_BUGREPORT=\"gfdl.climate.model.info@noaa.gov\" -DPACKAGE_URL=\"https://www.gfdl.noaa.gov/fms\" -DPACKAGE=\"FMS\" -DVERSION=\"2020.04\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_MPI_H=1 -DHAVE_NETCDF_H=1 -DHAVE_SCHED_GETAFFINITY=1 -DHAVE_MOD_MPI=1 -DHAVE_MOD_NETCDF=1 -DHAVE_CRAY_POINTER=1 -DHAVE_QUAD_PRECISION=1 -DHAVE_INTERNAL_NML=1 -Duse_netCDF=1 -Duse_libMPI=1 -I. -I../../../test_fms/mpp  -I../../../include -I../../.mod -I/opt/netcdf/4.6.1/INTEL/include/ -fopenmp  -O0 -g -traceback -check all -check noarg_temp_created -check nopointer -nowarn -ftz -auto -safe-cray-ptr -ftrapuv --I/opt/netcdf/4.6.1/INTEL/include/ -FR -real_size 64 -fopenmp -c ../../../test_fms/mpp/compare_data_checksums.F90
ifort: command line warning #10006: ignoring unknown option '-fI/opt/netcdf/4.6.1/INTEL/include/'
cp: cannot stat '../../.mods/compare_data_checksums.mod': No such file or directory
make[2]: *** [Makefile:1794: compare_data_checksums.mod] Error 1
mpiifort -DPACKAGE_NAME=\"GFDL\ FMS\ Library\" -DPACKAGE_TARNAME=\"FMS\" -DPACKAGE_VERSION=\"2020.04\" -DPACKAGE_STRING=\"GFDL\ FMS\ Library\ 2020.04\" -DPACKAGE_BUGREPORT=\"gfdl.climate.model.info@noaa.gov\" -DPACKAGE_URL=\"https://www.gfdl.noaa.gov/fms\" -DPACKAGE=\"FMS\" -DVERSION=\"2020.04\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_MPI_H=1 -DHAVE_NETCDF_H=1 -DHAVE_SCHED_GETAFFINITY=1 -DHAVE_MOD_MPI=1 -DHAVE_MOD_NETCDF=1 -DHAVE_CRAY_POINTER=1 -DHAVE_QUAD_PRECISION=1 -DHAVE_INTERNAL_NML=1 -Duse_netCDF=1 -Duse_libMPI=1 -I. -I../../../test_fms/mpp  -I../../../include -I../../.mod -I/opt/netcdf/4.6.1/INTEL/include/ -fopenmp  -O0 -g -traceback -check all -check noarg_temp_created -check nopointer -nowarn -ftz -auto -safe-cray-ptr -ftrapuv --I/opt/netcdf/4.6.1/INTEL/include/ -FR -real_size 64 -fopenmp -c ../../../test_fms/mpp/compare_data_checksums_int.F90
ifort: command line warning #10006: ignoring unknown option '-fI/opt/netcdf/4.6.1/INTEL/include/'
cp: cannot stat '../../.mods/compare_data_checksums_int.mod': No such file or directory
make[2]: *** [Makefile:1794: compare_data_checksums_int.mod] Error 1
mpiifort -DPACKAGE_NAME=\"GFDL\ FMS\ Library\" -DPACKAGE_TARNAME=\"FMS\" -DPACKAGE_VERSION=\"2020.04\" -DPACKAGE_STRING=\"GFDL\ FMS\ Library\ 2020.04\" -DPACKAGE_BUGREPORT=\"gfdl.climate.model.info@noaa.gov\" -DPACKAGE_URL=\"https://www.gfdl.noaa.gov/fms\" -DPACKAGE=\"FMS\" -DVERSION=\"2020.04\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_MPI_H=1 -DHAVE_NETCDF_H=1 -DHAVE_SCHED_GETAFFINITY=1 -DHAVE_MOD_MPI=1 -DHAVE_MOD_NETCDF=1 -DHAVE_CRAY_POINTER=1 -DHAVE_QUAD_PRECISION=1 -DHAVE_INTERNAL_NML=1 -Duse_netCDF=1 -Duse_libMPI=1 -I. -I../../../test_fms/mpp  -I../../../include -I../../.mod -I/opt/netcdf/4.6.1/INTEL/include/ -fopenmp  -O0 -g -traceback -check all -check noarg_temp_created -check nopointer -nowarn -ftz -auto -safe-cray-ptr -ftrapuv --I/opt/netcdf/4.6.1/INTEL/include/ -FR -real_size 64 -fopenmp -c ../../../test_fms/mpp/fill_halo.F90
ifort: command line warning #10006: ignoring unknown option '-fI/opt/netcdf/4.6.1/INTEL/include/'
cp: cannot stat '../../.mods/fill_halo.mod': No such file or directory
make[2]: *** [Makefile:1794: fill_halo.mod] Error 1
mpiifort -DPACKAGE_NAME=\"GFDL\ FMS\ Library\" -DPACKAGE_TARNAME=\"FMS\" -DPACKAGE_VERSION=\"2020.04\" -DPACKAGE_STRING=\"GFDL\ FMS\ Library\ 2020.04\" -DPACKAGE_BUGREPORT=\"gfdl.climate.model.info@noaa.gov\" -DPACKAGE_URL=\"https://www.gfdl.noaa.gov/fms\" -DPACKAGE=\"FMS\" -DVERSION=\"2020.04\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_MPI_H=1 -DHAVE_NETCDF_H=1 -DHAVE_SCHED_GETAFFINITY=1 -DHAVE_MOD_MPI=1 -DHAVE_MOD_NETCDF=1 -DHAVE_CRAY_POINTER=1 -DHAVE_QUAD_PRECISION=1 -DHAVE_INTERNAL_NML=1 -Duse_netCDF=1 -Duse_libMPI=1 -I. -I../../../test_fms/mpp  -I../../../include -I../../.mod -I/opt/netcdf/4.6.1/INTEL/include/ -fopenmp  -O0 -g -traceback -check all -check noarg_temp_created -check nopointer -nowarn -ftz -auto -safe-cray-ptr -ftrapuv --I/opt/netcdf/4.6.1/INTEL/include/ -FR -real_size 64 -fopenmp -c ../../../test_fms/mpp/test_mpp_update_domains_real.F90
ifort: command line warning #10006: ignoring unknown option '-fI/opt/netcdf/4.6.1/INTEL/include/'
cp: cannot stat '../../.mods/test_mpp_update_domains_real.mod': No such file or directory
make[2]: *** [Makefile:1794: test_mpp_update_domains_real.mod] Error 1
mpiifort -DPACKAGE_NAME=\"GFDL\ FMS\ Library\" -DPACKAGE_TARNAME=\"FMS\" -DPACKAGE_VERSION=\"2020.04\" -DPACKAGE_STRING=\"GFDL\ FMS\ Library\ 2020.04\" -DPACKAGE_BUGREPORT=\"gfdl.climate.model.info@noaa.gov\" -DPACKAGE_URL=\"https://www.gfdl.noaa.gov/fms\" -DPACKAGE=\"FMS\" -DVERSION=\"2020.04\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_MPI_H=1 -DHAVE_NETCDF_H=1 -DHAVE_SCHED_GETAFFINITY=1 -DHAVE_MOD_MPI=1 -DHAVE_MOD_NETCDF=1 -DHAVE_CRAY_POINTER=1 -DHAVE_QUAD_PRECISION=1 -DHAVE_INTERNAL_NML=1 -Duse_netCDF=1 -Duse_libMPI=1 -I. -I../../../test_fms/mpp  -I../../../include -I../../.mod -I/opt/netcdf/4.6.1/INTEL/include/ -fopenmp  -O0 -g -traceback -check all -check noarg_temp_created -check nopointer -nowarn -ftz -auto -safe-cray-ptr -ftrapuv --I/opt/netcdf/4.6.1/INTEL/include/ -FR -real_size 64 -fopenmp -c ../../../test_fms/mpp/test_mpp_update_domains_int.F90
ifort: command line warning #10006: ignoring unknown option '-fI/opt/netcdf/4.6.1/INTEL/include/'
cp: cannot stat '../../.mods/test_mpp_update_domains_int.mod': No such file or directory
make[2]: *** [Makefile:1794: test_mpp_update_domains_int.mod] Error 1
mpiifort -DPACKAGE_NAME=\"GFDL\ FMS\ Library\" -DPACKAGE_TARNAME=\"FMS\" -DPACKAGE_VERSION=\"2020.04\" -DPACKAGE_STRING=\"GFDL\ FMS\ Library\ 2020.04\" -DPACKAGE_BUGREPORT=\"gfdl.climate.model.info@noaa.gov\" -DPACKAGE_URL=\"https://www.gfdl.noaa.gov/fms\" -DPACKAGE=\"FMS\" -DVERSION=\"2020.04\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_MPI_H=1 -DHAVE_NETCDF_H=1 -DHAVE_SCHED_GETAFFINITY=1 -DHAVE_MOD_MPI=1 -DHAVE_MOD_NETCDF=1 -DHAVE_CRAY_POINTER=1 -DHAVE_QUAD_PRECISION=1 -DHAVE_INTERNAL_NML=1 -Duse_netCDF=1 -Duse_libMPI=1 -I. -I../../../test_fms/mpp  -I../../../include -I../../.mod -I/opt/netcdf/4.6.1/INTEL/include/ -fopenmp  -O0 -g -traceback -check all -check noarg_temp_created -check nopointer -nowarn -ftz -auto -safe-cray-ptr -ftrapuv --I/opt/netcdf/4.6.1/INTEL/include/ -FR -real_size 64 -fopenmp -c ../../../test_fms/mpp/test_domains_utility_mod.F90
ifort: command line warning #10006: ignoring unknown option '-fI/opt/netcdf/4.6.1/INTEL/include/'
cp: cannot stat '../../.mods/test_domains_utility_mod.mod': No such file or directory
make[2]: *** [Makefile:1794: test_domains_utility_mod.mod] Error 1
make[2]: Target 'check' not remade because of errors.
make[2]: Leaving directory '/home/Jessica.Liptak/FMS/build_intel/test_fms/mpp'
```

**Review by rem1776 — APPROVED** [review]

**Review by bensonr — APPROVED** [review]

**Review by thomas-robinson — APPROVED** [review]

**Pull request merged**
