### PR TITLE
Automated documentation hosting through GH pages

### PR DESCRIPTION
**Pull request by rem1776**
**Description**
Adds a github action that generates the documentation via doxygen and deploys it via Github Pages. The action is set to update the docs when run manually by users with write access and on version releases.

Essentially the generated docs are pushed to the 'gh-pages' branch and will then be automatically hosted at https://noaa-gfdl.github.io/FMS or a different url if set in the repo settings.

There also may be some changes to be made in the repo's settings for the first deployment(described [here](https://github.com/marketplace/actions/github-pages-action#%EF%B8%8F-first-deployment-with-github_token)), but on my fork I didn't need to make any changes.

**How Has This Been Tested?**
site deployed from my branch: https://rem1776.github.io/FMS 

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Comment by bensonr** [comment]
@rem1776 - If your site is how this initial drop will look, I suggest having the landing page mention it is a work in progress and barely scratches the surface of the capabilities of FMS.

**Comment by rem1776** [comment]
@bensonr The landing page is just the README straight from the repo but I can still add that in, i also repurposed #661 for the other more general doxygen updates I was gonna work on

**Comment by rem1776** [comment]
Leaving this as a draft until #661 is resolved

**Comment by rem1776** [comment]
I'm just gonna close this and include these changes with the actual doxygen comment updates for #661

**Pull request closed without merging**
