### PR TITLE
Adds a -DWITH_YAML option in cmake

### PR DESCRIPTION
**Pull request by uramirez8707**
**Description**
Adds a `-DWITH_YAML` option in cmake. The default is  `-DWITH_YAML=off`
Checks if the library exists and adds the `-Duse_yaml` macro to compile the yaml_parser code

Fixes # (issue)

**How Has This Been Tested?**
Compiles with cmake on skylake with intel.

```
mkdir build
cd build
cmake ..  -DWITH_YAML=on; make 
```
The build should compile as is.

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Comment by uramirez8707** [comment]
I am not sure if this is all that is needed. 
Can you take a look @rem1776?

**Comment by rem1776** [comment]
@uramirez8707 It wouldn't find the libyaml module on amd, so I needed to add an environment variable for a path that it can search in case it's installed somewhere CMake doesn't look by default. Figured it would be good to add an error message for the variable too.
 
Not really a cmake expert so you might know better than me, but this is what I had for the Findlibyaml file:
```
FIND_PATH(LIBYAML_INCLUDE_DIR  NAMES yaml.h  PATHS $ENV{LIBYAML_ROOT}/include ) 
FIND_LIBRARY(LIBYAML_LIBRARIES NAMES yaml    PATHS $ENV{LIBYAML_ROOT}/lib )
if(NOT LIBYAML_INCLUDE_DIR OR NOT LIBYAML_LIBRARIES)
  message(SEND_ERROR "libyaml library/include file not found, set LIBYAML_ROOT") 
endif()
MARK_AS_ADVANCED(LIBYAML_INCLUDE_DIR LIBYAML_LIBRARIES)
```

**Comment by uramirez8707** [comment]
@rem1776 Thats a good suggestions. Thanks.

**Comment by laurenchilutti** [comment]
@uramirez8707 Are you going to fix this so that all CI tests pass?

**Comment by thomas-robinson** [comment]
@rem1776 Should we add an action for testing cmake?  I thought there was one.  

@laurenchilutti can you make sure this works with your UFS build?

**Comment by laurenchilutti** [comment]
> @uramirez8707 Are you going to fix this so that all CI tests pass?

Nevermind! I see that the checks all passed.  I am testing with UFS today I will get back to you by the end of today.  So far I can confirm that FMS successfully built with this branch in cmake

**Comment by rem1776** [comment]
> @rem1776 Should we add an action for testing cmake? I thought there was one.

I think Mikyoung was planning on adding that a while ago cause there's an issue for it, but never got around to it. I'll try to add one it shouldn't take too long since its just building.

**Review by laurenchilutti — APPROVED** [review]
Tested with UFS and it passes

**Review by rem1776 — APPROVED** [review]

**Pull request merged**
