### PR TITLE
simple test for mpp_domains

### PR DESCRIPTION
**Pull request by edwardhartnett**
**Description**
More simple testing. There is a bunch of mpp_domain tests, but they are all skipped. Well, that's a bummer because I am working on this code for PIO integration, and I need some tests to figure out what is going on.

I hope that someday you fix your broken tests. In the meantime, here's a simple test, which works now, and which I can add to as needed to confirm that I understand what mpp domains are all about.

Part of #244 and #100 

**How Has This Been Tested?**
Tested on my GNU/Linux box.

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Comment by bensonr** [comment]
The mpp_domains tests aren't broken.  The issue is with the github CI area being resource limited for many of these tests.  Basic functionality requires a minimum of 6 mpi-ranks for the cubed-sphere related tests and to ensure domain creation and halo updates for the cubed-sphere and nests are unaffected requires more than six, ideally.     There are tests that can run on as few as 2 mpi-ranks and I agree these should be enabled.  I will work to ensure that happens.

**Comment by edwardhartnett** [comment]
Is there a limit on the number of MPI ranks that Travis allows? I believe I use as many as 16 in some netCDF testing...

**Comment by bensonr** [comment]
@edwardhartnett - I stand corrected.  I was able to run a travis test with 16 mpi-ranks as well.  Guess I was given bad info.  Regardless, I have most of the original mpp_domains tests running under travis and will soon have them in CI

**Comment by edwardhartnett** [comment]
@thomas-robinson I have added comments both at the top and throughout the test.

Also I have added more test code, and am now checking the values of the created domain objects.

**Comment by edwardhartnett** [comment]
This PR is ready to merge.

**Comment by colingladueNOAA** [comment]
Hi @edhartnett ,
Could you please have a look at this PR ( https://github.com/NOAA-GFDL/FMS/pull/453 ) and let me know which "test_level" you need for your mpp_init call for this test. We are trying to minimize how much of mpp_init is used by these tests, so we'd like to only use mpp_init up to the point that is necessary.

**Comment by edwardhartnett** [comment]
Test level 5.

Part of what I want from these tests is to have mpp behave the same way it does in an application. So I want it to do a full init.

I wonder why you are trying to limit mpp_init in this way? Testing right now is very quick, so why mess with it?

**Comment by thomas-robinson** [comment]
@colingladueNOAA this PR needs to run all of mpp_init, so the test level will not apply to this test.

**Comment by thomas-robinson** [comment]
@edhartnett the limits on using mpp_init are for testing the routines/functions that mpp_init calls.  The functions called in mpp_init all require that MPI in initialized and the mpp_initialized flag is set to .true.  Only an mpp function can set that flag, so we have to at least call that much of mpp_init. 

It seems silly to call all of mpp_init to test the routines that are in mpp_init.  mpp_pe(), for example, is used in mpp_init.  But if you call all of mpp_init, then you run mpp_pe before you test it. That's why we are limiting the  mpp_init calls for some tests.

This test should just run mpp_init.

**Comment by edwardhartnett** [comment]
I do not think you should be so concerned about running mpp_pe before you run it (again) to test it. The test still has value if it's called twice. 

Since this is an existing fortran code base, written without unit testing, no doubt some oddities will result in testing. For example, I'm a bit at a loss to know how to test that mpp_init() succeeded. Since the initialized flag is private, I can't check it in my test code, and there does not seem to be a getter function for that, which is fine.

So for the moment I'm not testing much except that mpp_init() can run without calling mpp_error() or segfaulting. Which is not much of a test, but useful in the debugger, and a worthwhile platform for future testing. ;-)

You should be careful about adding testing overhead in your production code. Best to keep all your test-related code separate, so that it can't get tangled up in serious bugs, performance issues, or just cluttering a codebase that's already complex enough.

**Comment by thomas-robinson** [comment]
@edhartnett thanks for the input.  We are trying to make as few modifications to the base code as possible related to testing.  The overhead is very minimal and only confined to mpp_init.  There were a few other ideas floated, and we ultimately selected this course of action to take moving forward for testing the functions contained in mpp_init.

**Pull request merged**
