### PR TITLE
Add extra safe-guard to pointer allocation when a pointer is passed as an argument

### LINKED ISSUE #1099: Allocated Pointers: Potential Memory Leak Issue
**Is your feature request related to a problem? Please describe.**
In horiz_interp and interpolator, some variables with the type of pointer are being allocated storage space with the use of the allocate statement.  With newer versions of Fortran, we now have access to the allocatable type.  The allocatable type is safer to use as storage will automatically be deallocated at end of a program.  With the pointer type, we can potentially cause memory leaks if we do not deallocate the pointer.

**Describe the solution you'd like**
Change any allocated pointers to allocatables.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by ganganoaa**
**Description**
This update relates to checking state of a pointer passed as an argument before reallocating it. In particular, the pointer argument, 'bc_rest_files',  is passed into subroutines 'CT_register_restarts_2d', 'CT_register_restarts_3d', 'mpp_io_CT_register_restarts_2d', and 'mpp_io_CT_register_restarts_3d' but its state is unknown. In order to avoid multiple allocations without freeing, checks are added before reallocation.

Fixes #1099 

**How Has This Been Tested?**
The update was tested with 'make check' and 'make distcheck' without any issues on OS, 'CentOS Stream 8'. The following setup was used for compiler, MPI wrapper, and required packages:

- oneapi v2022.2
- hdf5 v1.12.0
- tbb v2021.6.0
- oclfpga v2022.1.0
- netcdf v4.8.0
- mpi v2021.6.0 (Intel(R) MPI Library 2021.6)
- compiler-rt v2022.1.0
- compiler v2022.1.0

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Comment by thomas-robinson** [comment]
Is this only for mpp_io?

**Comment by thomas-robinson** [comment]
@uramirez8707 @mcallic2 should these routines just be removed?  They are named with `mpp_io` at the beginning.

**Comment by ganganoaa** [comment]
I don't think those routines are actually related to _mpp_io_.

**Comment by mcallic2** [comment]
Yea, what Uriel said lol. Best not to remove anything, that is why we ifdef'd the old io out

**Pull request closed without merging**
