### PR TITLE
Remove use_mpp_io from diag manager

### PR DESCRIPTION
**Pull request by thomas-robinson**
**Description**
Removes the variable `use_mpp_io` from the diag manager. 

Fixes # (issue)

**How Has This Been Tested?**
CI

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Review by bensonr — COMMENTED** [review]
Looks good from what I can see.

**Comment by GFDL-Eric** [comment]
@thomas-robinson This doesn't actually have any duplication from #928 since I wasn't sure whether or not to get rid of the use_mpp_io namelist flag (if anyone still uses it). Of course, I could incorporate these changes into #928 if we feel like they should go together.

**Comment by thomas-robinson** [comment]
Thanks @GFDL-Eric I think you should keep #928 as is, and let this be part of the diag manager modernization.  Then we can remove the rest of `use_mpp_io` in the "2022.05" end of year release.

**Review by GFDL-Eric — APPROVED** [review]

**Comment by GFDL-Eric** [comment]
@thomas-robinson sounds good!

**Review by bensonr — APPROVED** [review]

**Pull request merged**
