### PR TITLE
Fms2 io update: Compressed writes

### LINKED ISSUE #1218: Improve fms2_io performance
**Is your feature request related to a problem? Please describe.**

Doman Reads:
- In the current version of fms2_io, the io_root pe does 1 read for each of the pes and sends it to the other ranks, which is very inefficient

Compressed Writes:
- In the current version of fms2_io, the io_root_pe gathers and writes the data one PE at a time, instead of just doing one write

**Describe the solution you'd like**
Doman Reads:
- The root pe should do 1 read instead of multiple. The sending of the data should be non-blocking.

Compressed Writes:
- The root pe should gather all of the data and do one write instead of multiple.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by uramirez8707**
**Description**

1. Modified compressed_writes_1d/2d/3d
2. Extended mpp_gather to work for int8
3. Added unit tests to test all of the compressed writes interfaces
4. Compressed_writes_4d/5d were unchanged
   - Mpp_gather only support 1d, 2d and 3d arrays

Fixes #1218 

**How Has This Been Tested?**
CI
AM5 c384L66 amip experiment

**Checklist:**
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] New check tests, if applicable, are included
- [ ] `make distcheck` passes

### CODE REVIEW

**Review by ganganoaa — COMMENTED** [review]
Looks fine to me.

**Review by bensonr — APPROVED** [review]

**Comment by bensonr** [comment]
@uramirez8707 - will there also be fixes to compressed reads or are those handled in a different manner?

**Comment by uramirez8707** [comment]
@bensonr The compressed reads are handled differently in the land model code (as far as I can tell)

**Comment by bensonr** [comment]
> @bensonr The compressed reads are handled differently in the land model code (as far as I can tell)

@uramirez8707 - If I'm reading the fms2_io code correctly, it looks like the compressed_reads are doing a read/broadcast instead of a read_scatter.  Did I get that correct or am I mixing up domain and non-domain based file objects?

**Comment by uramirez8707** [comment]
@bensonr yes it is doing a read/broadcast of the whole grid so it really isn't a "compressed" read

**Comment by bensonr** [comment]
@uramirez8707  - thanks for confirming.  I didn't check the documentation, but hopefully that little nuance is stated somewhere.

**Review by rem1776 — APPROVED** [review]

**Pull request merged**
