### PR TITLE
Modifying several classes to use the "this" in type bound procedures.

### PR DESCRIPTION
**Pull request by ngs333**
This PR changes the dummy argument names in several classes for those functions
intended to be used as type bound procedure. The name of the first dummy argument,
intended to be the object that that procedure is attached to, is renames "this". This conforms
to existing conventions.

Fixes # (1020)

**How Has This Been Tested?**
The changes pass all the CI unit tests.

**Checklist:**
- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings
- [ X] Any dependent changes have been merged and published in downstream modules
- [ X] New check tests, if applicable, are included
- [ X] `make distcheck` passes

### CODE REVIEW

**Review by rem1776 — APPROVED** [review]

**Comment by thomas-robinson** [comment]
@ngs333 Why are there so many commits?

**Comment by ngs333** [comment]
The commits are there from the earlier work on the field weighting
function.  Ath the end of those commits there is one that removes it!
( So I dont think this PR picks up any of that work, and hopefully I will
soon re-add ino this for and branch that that earlier
field wheing function work again).

**Comment by thomas-robinson** [comment]
I tried to delete all of the details of the commits, but apparently that didn't work.

**Comment by thomas-robinson** [comment]
OK I cleaned up the commit message for this PR.

**Comment by thomas-robinson** [comment]
Resolves #1025

**Pull request merged**
