### PR TITLE
Diag manager combining 2020 and 2019 with -Duse_mpp_io flag

### PR DESCRIPTION
**Pull request by thomas-robinson**
**Description**
The diag_manager code from 2019.01.02 is added here and controlled with the compile-time flag -Duse_mpp_io.

Fixes #505 
Replaces #506

**How Has This Been Tested?**
`make check` on skylake with 
```bash
../configure FCFLAGS="-fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -sox -traceback -qopenmp `nf-config --fflags` -O0 " CPPFLAGS="`nc-config --cflags` -I/opt/intel/2019_up2/impi/2019.2.187/intel64/include/" FC="mpiifort" CC="mpiicc"
```
and 
```bash
../configure FCFLAGS="-fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -sox -traceback -qopenmp `nf-config --fflags` -O0 " CPPFLAGS="-Duse_mpp_io `nc-config --cflags` -I/opt/intel/2019_up2/impi/2019.2.187/intel64/include/" FC="mpiifort" CC="mpiicc"
```
Also tested with intel18 and intel19 on gaea using the experiment c96L33_am4p0_cmip6Diag

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Comment by thomas-robinson** [comment]
@GFDL-Eric do you think is approach will work in the other modules?  This is how I did it (and why I love csh)
```bash
git checkout 2019.01.02
cp -r diag_manager ..
git checkout master
git checkout -b dm_combine_2020_2019
# there is some diag_manifest stuff I had to do here
foreach f ( diag_axis.F90 diag_data.F90 diag_grid.F90 diag_manager.F90 diag_output.F90 diag_table.F90 diag_util.F90 diag_manifest.F90 )
 # put the ifdef below the license
 sed -i '19 i #ifndef use_mpp_io' diag_manager/${f}
 sed -i '$ a #else' diag_manager/${f}
 cat ../diag_manager/${f} >> diag_manager/${f}
 sed -i '$ a #endif' diag_manager/${f}
end
```

**Comment by GFDL-Eric** [comment]
Are you sure you didn't want to add `rm -rf .` and `echo "fms2_io is flawless and works as intended"` to the end of that script? Yeah, I mean aside from the visceral revulsion I have to that csh block, it seems like it should "function" like we expect (despite the fact that csh doesn't allow functions #cshburn). Hopefully we can implement it before we change the number of lines that the license takes up.

**Comment by thomas-robinson** [comment]
This doesn't work with mkmf because mkmf doesn't used the user defined `#ifdefs` to resolve dependencies.

**Comment by underwoo** [comment]
@thomas-robinson and others, please explain what it is the extra _script_ is attempting to solve, and why an additional `#ifdef` is required.  As you pointed out, `mkmf` cannot handle CPP macro file dependencies.  That will need to be handled by which files are passed to `mkmf` either through `list_paths` or on the `mkmf` command line.

Also, the auto tools build should add an option for the configure script to build with or without the `-Duse_mpp_io`.  Ideally, the user will not need to know the specific CPP macros when building with autotools or with CMake.

**Comment by thomas-robinson** [comment]
@underwoo we updated to work with auto tools and mkmf.  #526 updated the configure and adds n addition test to the travis build.  I tested with intel18 on gaea using the experiment c96L33_am4p0_cmip6Diag

**Comment by thomas-robinson** [comment]
@underwoo this `#ifdef` is being used as a compile time switch for selecting whether to use mpp_io or fms2_io in the routines that use IO within fms.  The script above just adds the `#ifdef` to the files.  It had to be modified to make sure only one `module and `end module` pairing was in the file for compatibility with mkmf.  @GFDL-Eric also made a script that does a similar thing for a single file in #517

**Comment by thomas-robinson** [comment]
Thanks @underwoo I will try to keep full file swaps to the files that really need it.  I think that's diag_output.F90 (for sure) and diag_util.F90.

**Comment by thomas-robinson** [comment]
I'm closing this and replacing it with #509 which is a little cleaner

**Pull request closed without merging**
