### PR TITLE
Revert "Final stage of bats removal, all tests converted to use shell scripts"

### PR DESCRIPTION
**Pull request by wrongkindofdoctor**
Reverts NOAA-GFDL/FMS#228

### CODE REVIEW

**Comment by wrongkindofdoctor** [comment]
Merge failed the travis CI check

**Comment by edwardhartnett** [comment]
Perhaps stand by a moment, and let me look at what is not passing travis.

Probably it is a result of some merged code, since the PR passed travis.

**Comment by edwardhartnett** [comment]
@wrongkindofdoctor not sure why this is needed. Current master passes travis for me, as well as my own Jenkins-based CI system.

What errors are you seeing that would call for this rollback?

**Comment by wrongkindofdoctor** [comment]
Tests are passing correctly, I'm closing this PR.

**Pull request closed without merging**
