### PR TITLE
Add GitHub action tests

### LINKED ISSUE #338: GitHub Actions
**Is your feature request related to a problem? Please describe.**
The new GitHub actions allow more control over the test outcome than the Travis CI.  We should begin migrating our CI tests to GitHub actions.

**Describe the solution you'd like**
Most of the tests in FMS should be run through GitHub actions.  We can still use other CI (e.g. Travis) when those have options we cannot test through GitHub, for example using ARM processors.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by underwoo**
**Description**
Add a build test (replaces the Travis CI test, and a lint test for trailing whitespace and tab characters in Fortran files.

Fixes #338

**How Has This Been Tested?**
Only adds GitHub actions.  Test will be conducted via GitHub actions.

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Comment by underwoo** [comment]
The lint test is failing, and it will continue to fail until the nest update is pulled in.  

A few additional tests will be added.  Some of those will also fail until the problem(s) are addressed.

**Comment by underwoo** [comment]
lint is still failing due to trailing whitespace.  The files are listed below.  I think we should get this in place now, and stop using Travis CI for future merges.  I will create an issue to resolve the tailing whitespace.

```
./configure.ac
./axis_utils/axis_utils2.F90
./exchange/xgrid.F90
./block_control/block_control.F90
./drifters/drifters_core.F90
./CHANGELOG.md
./diag_manager/diag_util.F90
./diag_manager/diag_output.F90
./diag_manager/diag_manager.F90
./topography/topography.F90
./.github/CODEOWNERS
./fms2_io/blackboxio.F90
./fms2_io/netcdf_io.F90
./docs/Doxyfile.in
./test_fms/mpp/test_read_input_nml.F90
./test_fms/mpp/test_mpp_pe.F90
./test_fms/mpp/test_clock_init.F90
./test_fms/mpp/test_read_ascii_file.F90
./test_fms/mpp/test_stdout.F90
./test_fms/mpp/test_mpp_broadcast.F90
./test_fms/mpp/test_domains_simple.F90
./test_fms/mpp/test_system_clock.F90
./test_fms/mpp/test_mpp_npes.F90
./test_fms/mpp/test_mpp_domains2.sh
./test_fms/fms2_io/test_io_with_mask.F90
./test_fms/fms2_io/test_io_simple.F90
```

**Comment by GFDL-Eric** [comment]
It was my understanding that there should be trailing whitespace in markdown, so I did not remove the trailing whitespace from that document. However, I ran my "remove trailing whitespace" vim macro through all the other files and pushed it here https://github.com/GFDL-Eric/FMS/tree/whitespace_fix I'm not sure if you wanted to merge that in to your branch @underwoo ?

**Comment by GFDL-Eric** [comment]
So all of the files are updated, but obviously the linter still fails because of the markdown file. Is there any way to exclude a specific file from the lint check?

**Comment by GFDL-Eric** [comment]
OK, upon further review trailing whitespace in markdown, while supported, is not considered proper form. I've updated the proper commit

**Review by thomas-robinson — DISMISSED** [review]

**Comment by thomas-robinson** [comment]
@underwoo is there a reason this is still a draft? Can we merge it now?

**Review by rem1776 — DISMISSED** [review]

**Comment by underwoo** [comment]
Let me update the branch to be off the latest master, then I'll remove the draft status.  I hope to have something by EOB tomorrow.

**Comment by underwoo** [comment]
> I hope to have something by EOB tomorrow.

Done.

**Review by bensonr — COMMENTED** [review]
I don't really know much about GitHub actions and will defer to others with more experience.

**Comment by thomas-robinson** [comment]
@bensonr this will be a learning experience for all of us.

**Review by wrongkindofdoctor — APPROVED** [review]

**Comment by underwoo** [comment]
@thomas-robinson I think you may have changed the GitHub Actions tests as required too soon.  Until this PR is merged, and all PRs will show pending actions.  I don't know if all PRs will need to merge in master to pass, or if Actions will do a merge test.  We'll need to see.

**Comment by thomas-robinson** [comment]
@underwoo Once this is done we will find out.  I think there are only 3 PRs that are pending to go in for 2021.01.

**Review by thomas-robinson — APPROVED** [review]
The travis removal is in #641 so this is alright with me

**Review by bensonr — APPROVED** [review]

**Review by GFDL-Eric — APPROVED** [review]

**Review by rem1776 — APPROVED** [review]

**Pull request merged**
