### PR TITLE
Adds unit test for get_ascii_file_num_lines

### PR DESCRIPTION
**Pull request by GFDL-Eric**
**Description**
This is a suite of unit tests (currently 5 tests but may be expanded) for the get_ascii_file_num_lines mpp function.

Fixes # (issue)

**How Has This Been Tested?**
Ran make distcheck as well as make check in the mpp folder. This was with Intel19 on the Skylake box.

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Comment by GFDL-Eric** [comment]
Still queuing in Travis... even after re-submitting on a new PR (and using a new branch). It's also unclear why just the one Test is stuck, when the other ones goes off without a hitch.

**Comment by colingladueNOAA** [comment]
There are some other suggestions here: https://travis-ci.community/t/travis-ci-branch-expected-waiting-for-status-to-be-reported/829/2 , but I cannot guarantee that they will work every time. This seems to be becoming too common of a problem and I hope we can find a long term solution soon.

**Comment by GFDL-Eric** [comment]
@colingladueNOAA That article seemed to suggest that I enable Travis CI for my GitHub account and then activate it for my fork. Is that something I should do or is there some reason I shouldn't proceed with that (possible GFDL security issue?)

**Comment by thomas-robinson** [comment]
@GFDL-Eric a lot of us have travis turned on in our forks

**Pull request closed without merging**
