### PR TITLE
Introducing Grid2

### PR DESCRIPTION
**Pull request by GFDL-Eric**
**Description**
Adds grid2.F90 to the mosaic directory to eliminate the need for fms_io in these grid calls. Init and end routines were introduced (and put in fms) to minimize the number of file open calls.

Fixes # (issue)

**How Has This Been Tested?**
Tested in 2021.02-alpha1 lm4p1 land tests

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [ ] `make distcheck` passes

### CODE REVIEW

**Comment by rem1776** [comment]
@GFDL-Eric It looks like it can't find the compiled modulefile for grid2 when compiling in the CI. I think if you change fms to be after mosaic in the top level makefile.am directory list it should fix it.

**Comment by GFDL-Eric** [comment]
@rem1776 I guess that didn't work? I'm not sure if there's a different issue now?

**Comment by rem1776** [comment]
@GFDL-Eric Looks like the same issue, just with a different module. I'm not sure if there's an ordering that would work or if it's some kind of circular dependency.

**Comment by GFDL-Eric** [comment]
ok so the reordering sort of worked, but now I need to get rid of any fms dependencies in the entirety of the mosaic folder... classic

**Comment by GFDL-Eric** [comment]
oof, I guess that includes fms_io mod since that's in the fms folder... which isn't going to work. I'm going to have to rethink this a bit. Ideas welcome!

**Comment by GFDL-Eric** [comment]
I've tried a ton of stuff here including separating mosaic2.F90 and grid2.F90 into their own directory, to no avail. Maybe I'm missing something obvious with the Makefile or configure.ac?

**Comment by rem1776** [comment]
I was just about to suggest those last changes. I got it to compile on gcc (hopefully it'll work with the ci too) with those changes plus
`nodist_include_HEADERS = $(MODFILES)`

And i also had to add paranthesis to the get_great_circle_algorithm header for some reason.

**Comment by GFDL-Eric** [comment]
@rem1776 I implemented the changes and it seems like now the failure is outside the realm of grid2 and is just a data_override test failure? I'm not sure if this was failing on other PRs as well or if it's because of something I did.

**Comment by rem1776** [comment]
Yeah it looks like it failed from
`FATAL from PE     0: NetCDF: Variable not found`
I'm not sure why it would fail for this PR though, I don't think the data_override test uses anything from this. I re-ran it before and it failed the same way so I don't think its the normal sporadic failures from input files but I'll see if it happens with gcc too

**Review by rem1776 — APPROVED** [review]
Nice that fixed it, guess i was wrong

**Pull request merged**
