### PR TITLE
Add hit count to timers

### PR DESCRIPTION
**Pull request by ofuhrer**
**Description**
This PR add a new feature to the timers (main API `mpp_clock_id`, `mpp_clock_begin`, `mpp_clock_end`) which collects how many times a timer section is actually hit in the code. The hit count from the MPI master rank is reported.

**How Has This Been Tested?**
Introduced in fv3gfs and tested with GNU and Intel compilers (debug and opt mode) on the Piz Daint supercomputer for a simple c48 testcase.

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Comment by rem1776** [comment]
@ofuhrer thanks for contributing, can I ask why you wanted to add this feature to FMS?

**Comment by ofuhrer** [comment]
@rem1776 thanks for taking a look. imho hit counts are useful for two purposes:
1) compute per call execution times of code sections
2) consistency checks to make sure the reported timers are actually correct
does that make sense and is also potentially of interest for others?

**Comment by bensonr** [comment]
@ofuhrer @rem1776 - Oli and I discussed this prior to him putting in the issue/PR.  This is a useful addition to see how many times a section of code being timed was executed.

**Review by bensonr — DISMISSED** [review]
Thanks @ofuhrer, this all looks good.

**Review by wrongkindofdoctor — DISMISSED** [review]

**Comment by rem1776** [comment]
@ofuhrer When you get a chance, could you fix the new merge conflicts so I can merge this in. Thanks!

**Comment by thomas-robinson** [comment]
@ofuhrer also be sure to check off all of the boxes in your description.  If the box does not apply, check it.

**Comment by ofuhrer** [comment]
@rem1776 @thomas-robinson Done. The automatic replacement of the integer, real kind seems to have broken the indentation in places, so I fixed that as well.

**Review by bensonr — APPROVED** [review]

**Review by wrongkindofdoctor — APPROVED** [review]

**Pull request merged**
