### PR TITLE
FMS2io: domain_write fix 

### LINKED ISSUE #362: FMS2 send_data crashes when ocean has mask_table, NetCDF: Index exceeds dimension bound
**Describe the bug**
When we use a mask_table for the ocean the model crashes like this:
```
FATAL from PE  1152: NetCDF: Index exceeds dimension bound
Rank 1152 [Thu Mar 26 02:34:39 2020] [c5-0c1s12n0] application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1152
forrtl: error (76): Abort trap signal
Image              PC                Routine            Line        Source
fms_esm4.1_sis2_c  000000000364C3D6  mpp_mod_mp_mpp_er          69  mpp_util_mpi.inc
fms_esm4.1_sis2_c  00000000031D8020  fms_io_utils_mod_         145  fms_io_utils.F90
fms_esm4.1_sis2_c  000000000327CA6B  netcdf_io_mod_mp_         238  netcdf_io.F90
fms_esm4.1_sis2_c  00000000030B2E9A  fms_netcdf_domain         672  domain_write.inc
fms_esm4.1_sis2_c  00000000036748FF  diag_output_mod_m        1341  diag_output.F90
fms_esm4.1_sis2_c  000000000322F4F8  diag_util_mod_mp_        2629  diag_util.F90
fms_esm4.1_sis2_c  0000000003099090  diag_manager_mod_        3518  diag_manager.F90
fms_esm4.1_sis2_c  00000000030873B3  diag_manager_mod_        2008  diag_manager.F90
fms_esm4.1_sis2_c  000000000307742D  diag_manager_mod_        1550  diag_manager.F90
fms_esm4.1_sis2_c  000000000238480A  mom_diag_mediator         901  MOM_diag_mediator.F90
fms_esm4.1_sis2_c  000000000255E5C1  mom_diagnostics_m        1141  MOM_diagnostics.F90
fms_esm4.1_sis2_c  0000000002221B0B  mom_mp_step_mom_          836  MOM.F90
fms_esm4.1_sis2_c  000000000219BB7F  ocean_model_mod_m         556  ocean_model_MOM.F90
```

**To Reproduce**
Run either ESM4 or OMIP experiment that uses a mask_table for the ocean.

**Expected behavior**
Here are the stdouts for the same ocean layout with and without a mask_table

crash with mask_table
```
/lustre/f2/scratch/Niki.Zadeh/FMS2020.01_mom6_ESM4_v1.0.3uu_1/ESM4_piControl_D/ncrc3.intel18-prod-openmp/stdout/run/ESM4_piControl_D_1x0m2d_216x4a_442x1o.o202928844 
```
Expected without mask_table
```
/lustre/f2/scratch/Niki.Zadeh/FMS2020.01_mom6_ESM4_v1.0.3uu_1/ESM4_piControl_D/ncrc3.intel18-prod-openmp/stdout/run/ESM4_piControl_D_1x0m2d_216x4a_512x1o.o202928845
```
**System Environment**
Describe the system environment, include:
- OS: c3 and c4 with fre/test
- Compiler(s): Intel18
- MPI type, and version (e.g. MPICH, Cray MPI, openMPI)
- netCDF Version: For both C and Fortran
- Configure options: Any additional flags, or macros passed to configure

**Additional context**
Add any other context about the problem.  If applicable, include where any files
that help describe, or reproduce the problem exist.

There is a similar issue with ocean-ice runs (which are smaller and easier to debug):
```
/lustre/f2/scratch/Niki.Zadeh/FMS2020.01_mom6_ESM4_v1.0.3_0/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200/ncrc3.intel18-prod/stdout/run/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200_1x0m2d_442x1o.o202928898

/lustre/f2/scratch/Niki.Zadeh/FMS2020.01_mom6_ESM4_v1.0.3_0/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200/ncrc3.intel18-prod/stdout/run/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200_1x0m2d_512x1o.o202928897
```

### PR DESCRIPTION
**Pull request by uramirez8707**
**Description**
This uses the min value of pe_isc/pe_jsc to assign c instead of pe_isc(1)/pe_jsc(1)

This gets us pass the `NetCDF: Index exceeds dimension bound` error, **but** there is still something wrong with the regional diagnostics. 

Fixes #362 

**How Has This Been Tested?**
AM4.0 with intel18 in debug, prod, repro with/without openmp. 

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Comment by uramirez8707** [comment]
@menzel-gfdl

**Comment by menzel-gfdl** [comment]
@uramirez8707 Looks good to me.

**Comment by thomas-robinson** [comment]
I want to run a few tests before you merge this in.

**Comment by colingladueNOAA** [comment]
@thomas-robinson  Have you completed your tests on this?

**Comment by thomas-robinson** [comment]
@colingladueNOAA yes thank you.

**Pull request merged**
