### PR TITLE
Resolves #269.  Any variable that was named `pos` is now named `domain_position`

### LINKED ISSUE #269: diag_manager "pos" argument is inconsistent
**Is your feature request related to a problem? Please describe.**
[diag_axis_init](https://github.com/NOAA-GFDL/FMS/blob/master/diag_manager/diag_axis.F90#L156) has an optional argument `pos`, but the fms2_io uses `domain_position` as its argument.  These are inconsistent

**Describe the solution you'd like**
diag_axis_init and other subroutines should be updated to use `domain_position` instead of `pos`

**Describe alternatives you've considered**

**Additional context**
This requires update to other repos where the `pos` argument is used in diag_axis_init

### PR DESCRIPTION
**Pull request by thomas-robinson**
**Description**
All variables in the diag_manager named `pos` have been renamed `domain_position`
Requires updates to atmos_cubed_sphere

Fixes # (issue)
#269 

**How Has This Been Tested?**
passed travis CI checks

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Comment by thomas-robinson** [comment]
@ngs333 is listed as a code owner in the CODEOWNERS file, but he was not assigned as a reviewer.

**Comment by underwoo** [comment]
> @ngs333 is listed as a code owner in the CODEOWNERS file, but he was not assigned as a reviewer.

I think that is b/c @ngs333 hasn't accepted the invite to be a member of the NOAA-GFDL organization.  It appears, from the codeowners documentation, that only team members will be assigned as reviewers.

**Comment by thomas-robinson** [comment]
We are making the appropriate changes in NOAA-GFDL/GFDL_atmos_cubed_sphere#15 .  We should probably wait to merge until that is complete.  I know @nikizadehgfdl was also looking at using this functionality somewhere in the ice model.

**Comment by underwoo** [comment]
Please add something in the CHANGELOG.md file (under the unreleased
section) to indicate this change.  We need to start adding brief
descriptions of changes in that file, and verify the information is
included before performing a merge.  I'll get something that will update
the PR template to include a checkbox.

--
Seth Underwood

S/W Development Process Lead
Modeling Systems Group
GFDL/NOAA/DOC
201 Forrestal Road
Princeton, NJ 08540-6649

(609) 452-5847 Office
(304) 376-9002 Cell
(609) 987-5063 Fax
Seth.Underwood@noaa.gov

**Comment by bensonr** [comment]
With coordination, I can merge [NOAA-GFDL/GFDL_atmos_cubed_sphere#15](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/15) at the same time this PR is merged.

**Comment by wrongkindofdoctor** [comment]
@bensonr @thomas-robinson I will merge it in as soon as you confirm.

**Comment by bensonr** [comment]
@bensonr is ready when @thomas-robinson and @laurenchilutti confirm

**Comment by thomas-robinson** [comment]
@bensonr i think NOAA-GFDL/GFDL_atmos_cubed_sphere#14 need to come first so that all of the xanadu-tagged code works together.  Then NOAA-GFDL/GFDL_atmos_cubed_sphere#15 should be merged after.

**Comment by bensonr** [comment]
@thomas-robinson I will do both at the same time.

**Comment by thomas-robinson** [comment]
@underwoo I updated the change log.

**Pull request merged**
