### PR TITLE
Fix a typo causing incorrect results or segmentation fault.

### LINKED ISSUE #623: mpp_get_UG_domain_tile_pe_inf does not return information in arguments correctly
**Describe the bug**
Subrutine `mpp_get_UG_domain_tile_pe_inf` incorrectly uses optional arguments, resulting in segmentation fault if `npes` is present, but `root_pe` is not; returns incorrect number of `npes` in either case.

**To Reproduce**
```
  integer tile_npes
  ...
  call mpp_get_UG_domain_tile_pe_inf(lnd%ug_domain, npes=tile_npes)
```
Model crashes with SIGSEGV:
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
fms_code.x         00000000015E565D  Unknown               Unknown  Unknown
fms_code.x         0000000000F16060  Unknown               Unknown  Unknown
fms_code.x         0000000000A10B0C  mpp_domains_mod_m         534  mpp_unstruct_domain.inc
...
```
**Expected behavior**
call finishes successfully and return correct values for optional arguments, in any combination of presence or absence. 

**System Environment**
Describe the system environment, include:
- OS: SUSE Linux Enterprise Server 15 SP1
- Compiler(s): Intel 18.0.6.288

### PR DESCRIPTION
**Pull request by slm7826**
number of processors was assined to a wrong optional argument.

**Description**
Fix a typo causing segmentation fault or incorrect results returned from `mpp_get_UG_domain_tile_pe_inf`

Fixes #623

### CODE REVIEW

**Review by wrongkindofdoctor — APPROVED** [review]

**Comment by thomas-robinson** [comment]
@slm7826 can you merge the current master into your branch?  Hopefully that will kick off the CI testing so this can be merged.

**Review by bensonr — APPROVED** [review]

**Comment by slm7826** [comment]
Done.

Interesting, it looks like I cannot reply in GitHub interface: “Comment” button dimmed out.

Cheers,
—
Sergey

**Comment by thomas-robinson** [comment]
@slm7826 How pressing is this?  Do you want it in the next release, or can it wait?  We just started testing a possible release candidate.

**Comment by slm7826** [comment]
Not very pressing: I have to work around it in anyway, since I want my code to work with previous releases too.

**Comment by rem1776** [comment]
@slm7826 We've migrated our CI testing to Github Actions, when you get a chance please merge with master so this PR can go through the testing.

**Review by rem1776 — APPROVED** [review]

**Pull request merged**
