### PR TITLE
Use flush function

### LINKED ISSUE #627: Converts with call flush() calls in FMS (and MOM6) to Standard flush()
**Is your feature request related to a problem? Please describe.**

This was brought up in https://github.com/NOAA-GFDL/MOM6/pull/1165#issuecomment-733916634, we (the GEOS developers) found that when using Intel Fortran on macOS (and maybe on Linux) that, for some reason, Intel was getting confused by `call FLUSH()` calls found in FMS and MOM6. This is probably because the `call FLUSH()` subroutine is a Fortran extension. So we've been internally in GEOS and in our forks, converting all the `call FLUSH()` to use the Fortran Standard `FLUSH()` intrinsic (which I think every good Fortran compiler now should support) and that seems to be helping.

@tclune might be able to provide more info.

**Describe the solution you'd like**

Convert all `call flush()` to use the Fortran Standard intrinsic `flush()`

**Describe alternatives you've considered**

We've been maintaining forks of FMS (and MOM6) with this change.

### PR DESCRIPTION
**Pull request by mathomp4**
**Description**

Converts all `call flush()` in FMS to be `flush()` as mentioned in #627.

Fixes #627 

**How Has This Been Tested?**

We have been running with the `call flush()`->`flush()` in GEOS' FMS and MOM6 for a while, but I will note that we are still on 2019.03. I've made this PR against `master` because that follows the [contributing guidelines](https://github.com/NOAA-GFDL/FMS/blob/6d3ac620423e7ede412e4bb1b36c338775d95193/CONTRIBUTING.md). But as GEOS doesn't run with `master` FMS (yet), I can't test it directly.

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [ ] `make distcheck` passes

### CODE REVIEW

**Review by bensonr — APPROVED** [review]

**Review by wrongkindofdoctor — APPROVED** [review]

**Comment by thomas-robinson** [comment]
@mathomp4 please check all boxes in the checklist.  If the box was no required for this update, then check it anyway. 

The travis-ci didn't run for some reason.  Have you tried compiling this and running `make distcheck`?

**Comment by mathomp4** [comment]
> @mathomp4 please check all boxes in the checklist. If the box was no required for this update, then check it anyway.
> 
> The travis-ci didn't run for some reason. Have you tried compiling this and running `make distcheck`?

@thomas-robinson I just did a build locally with:
```console
autoreconf -vfi
./configure --prefix=$HOME/throwaway-FMS CPPFLAGS="$(nf-config --cflags)" FCFLAGS="$(nf-config --cflags)" LDFLAGS="$(nf-config --flibs)" CC=mpicc CXX=mpic++ FC=mpifort
make -j6 |& tee make.log
make distcheck |& tee makedistcheck.log
```
and then it got weird: 
[makedistcheck.log](https://github.com/NOAA-GFDL/FMS/files/5624777/makedistcheck.log)

Maybe this is a BSD tar vs GNU tar thing?

**Comment by wrongkindofdoctor** [comment]
FYI, TravisCI didn't run because the lab used up the monthly credits allotted for the NOAA-GFDL account. FMS, MDTF, and MOM6 all run Travis tests, so it's going to become more of an issue as all of the groups expand CI testing.

**Comment by mathomp4** [comment]
> FYI, TravisCI didn't run because the lab used up the monthly credits allotted for the NOAA-GFDL account. FMS, MDTF, and MOM6 all run Travis tests, so it's going to become more of an issue as all of the groups expand CI testing.

@wrongkindofdoctor Yeah, we just hit this here as well. Ugh. Time for a lot of GitHub Actions and CircleCI maybe...

**Comment by underwoo** [comment]
We need to migrate to GitHub Actions.  From the documentation, Actions have no limit for public repositories -- that is if I'm reading it correctly.

**Comment by mathomp4** [comment]
> We need to migrate to GitHub Actions. From the documentation, Actions have no limit for public repositories -- that is if I'm reading it correctly.

No limit...yet. 😄  But, yes, CircleCI and GitHub Actions seem to be the two best free bets now. On each, `make -j4` is about the best you can do on the free plans.

**Comment by rem1776** [comment]
@mathomp4 We've migrated our CI testing to Github Actions, when you get a chance please merge with master so this PR can go through the CI.

**Comment by mathomp4** [comment]
Okay. I think I merged correctly. We shall find out.

**Review by rem1776 — APPROVED** [review]

**Pull request merged**
