### PR TITLE
WIP - initialize buffers to zero

### LINKED ISSUE #447: FMS 2020.03-alpha1 cause crashes in diag_manager_end with NetCDF: Numeric conversion not representable
**Describe the bug**
Restart regression tests of two different models crash in diag_manager_end in the second leg of experiemnt with the following traceback: 

```
FATAL from PE  1728: NetCDF: Numeric conversion not representable

Image              PC                Routine            Line        Source
fms_esm4.1_sis2_c  00000000053606F6  Unknown               Unknown  Unknown
fms_esm4.1_sis2_c  000000000337C913  mpp_mod_mp_mpp_er          68  mpp_util_mpi.inc
fms_esm4.1_sis2_c  00000000031145D0  fms_io_utils_mod_         164  fms_io_utils.F90
fms_esm4.1_sis2_c  00000000030B872B  netcdf_io_mod_mp_         284  netcdf_io.F90
fms_esm4.1_sis2_c  00000000034A69CA  fms_netcdf_domain         834  domain_write.inc
fms_esm4.1_sis2_c  000000000348619F  diag_output_mod_m        1270  diag_output.F90
fms_esm4.1_sis2_c  0000000003195648  diag_util_mod_mp_        2538  diag_util.F90
fms_esm4.1_sis2_c  0000000003461CF0  diag_manager_mod_        3542  diag_manager.F90
fms_esm4.1_sis2_c  000000000345F402  diag_manager_mod_        3760  diag_manager.F90
fms_esm4.1_sis2_c  0000000000416906  coupler_main_IP_c        1995  coupler_main.F90
fms_esm4.1_sis2_c  000000000040CD9D  MAIN__                   1151  coupler_main.F90
```

**To Reproduce**
```
git clone -b RTS https://gitlab.gfdl.noaa.gov/mdt/xml mdt_xml_FMS2020.03
cd mdt_xml_FMS2020.03
fremake -x OM4_COBALT_postxanadu.xml -p ncrc4.intel18 -t prod MOM6_SIS2_compile
frerun -x OM4_COBALT_postxanadu.xml -p ncrc4.intel18 -t prod OM4p5_CORE2_IAF_COBALT_abio_csf_mle200 -r rts --no-transfer -u -s
```

**Expected behavior**
RTS should not crash!

**System Environment**
gaea and orion

**Additional context**
On gaea I see this only if the test has a restart in the middle, but on orion it happens on 1 segment  runs too. Also, I see this only in tests using a ocean mask_table, so this might be @ngs333 old friend issue #409  back in a new suit. 

ESM4 crashes on gaea:
```
/lustre/f2/scratch/Niki.Zadeh/FMS2020.03-alpha1min_mom6_ESM4_v1.0.3min_1/ESM4_piControl_D/ncrc4.intel18-prod-openmp/stdout/run/ESM4_piControl_D_2x0m15d_1728x4a_1437x1o.o268648259
```
OM4 crashes on gaea:
```
/lustre/f2/scratch/Niki.Zadeh/FMS2020.03-alpha1_mom6_ESM4_v1.0.3_min_0604_1/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200/ncrc4.intel18-prod/stdout/run/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200_2x0m15d_1057x1o.o268647635
```
OM4 crashes on orion:
```
OK
/work/noaa/gfdlscr/nzadeh/FMS2020.03-alpha1_mom6_ESM4_v1.0.3_min/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200/orion.intel18-prod/stdout/run/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200_1x0m2d_442x1o.o73362 

Crash
/work/noaa/gfdlscr/nzadeh/FMS2020.03-alpha1_mom6_ESM4_v1.0.3_min/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200/orion.intel18-prod/stdout/run/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200_1x0m2d_442x1o6.o73533
```

### PR DESCRIPTION
**Pull request by menzel-gfdl**
**Description**
Initializes global buffers to zero.  This prevents the buffer from containing uninitialized values when it is passed to netCDF to be written, which appears to be the cause of the crashes in the linked issue.

Fixes #447

**How Has This Been Tested?**
I ran a 2-day simulation with a mask table, but since I was re-using someone else's work directory I don't know the specifics.  @nikizadehgfdl  and @ngs333, can you please try this branch in your tests?  If it passes, then I will remove the WIP label.

**Checklist:**
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] New check tests, if applicable, are included
- [ ] `make distcheck` passes

### CODE REVIEW

**Comment by thomas-robinson** [comment]
Initializing the buffers seems dangerous.  Shouldn't netcdf be able to handle NaNs?  Isn't that just missing data in netcdf?

**Comment by ngs333** [comment]
I merged this code into a copy of 2020.03-alpha1 and tested. Application does not crash with my tests. Hopefully NikiZadeh can perform additional tests.

**Comment by menzel-gfdl** [comment]
@thomas-robinson I agree this is dangerous, that's why I put a WIP.  But I think it proves that the patch I added to improve the writes tries to write uninitialized data in this specific case.  We need to work through why.

**Comment by ngs333** [comment]
It appears that in Xanadu the written buffers are totally (completely) pre-filles with a default fill value. The remaining issue is what should that value be.

In file mpp_io_unstructured_write.inc,subroutine subroutine mpp_io_unstructured_write_r_1D
provides the simplest example starting with line 125:
 if (mpp_pe() .eq. pelist(1)) then
        allocate(cdata(nelems))
        cdata = fill
        do i = 1,nelems
            cdata(i) = rbuff(i)
        enddo
        field%size(1) = nelems
        call write_record_default(funit, &
                        field, &
                                  nelems, &
                                  cdata, & ...
          
cdata is whats written and its initialized with line "cdata = fill" before it is filled with the passed in data. The relevant basic logic is the same in other functions like mpp_io_unstructured_write_r_2D and  MPP_WRITE_COMPRESSED_2D_.

Although the mpp_write functions have this logic:
  fill = 0
  if(PRESENT(default_data)) fill = default_data
 in xanadu,  as far as I can tell, default_data is always provided by the diag_manager. 

My opinion is that fms2_io should :
1) initialize the buffer before its written with the target data
2) .(for the moment) only initialize using the default provided by the diag_manager, and have a check to force the diag_manage to provide the default.
3) Once it works completely correct, put in logic equivalent to the the xanadu one of:
    fill = 0
  if(PRESENT(default_data)) fill = default_data
 and also print a warning if the diag_manager does not provide a default fill value.

**Comment by ngs333** [comment]
This issue should be closed by the merge of Issue 496 (https://github.com/NOAA-GFDL/FMS/pull/496), which initialized also
added code to initialize the buffers.

**Comment by thomas-robinson** [comment]
@ngs333 #496 was merged.  Should this be closed?  @menzel-gfdl and @uramirez8707 any objections?

**Comment by menzel-gfdl** [comment]
@thomas-robinson yes I think this should be closed.  #496 is a much better fix.

**Comment by ngs333** [comment]
Agree on closing do to #496.

**Pull request closed without merging**
