### PR TITLE
Collective message passing support for load_xgrid

### PR DESCRIPTION
**Pull request by marshallward**
This replaces the point-to-point messages inside exchange grid
initialization (`load_xgrid`) with MPI_Alltoall collective calls.

Using collectives yields a significant performance improvement when
`nsubset` is not used, and a slight improvement over optimal values of
`nsubset`.  This also prevents potential model hangs on certain
platforms and MPI libraries which cannot cope with very large numbers of
messages.

Xgrid collectives are enabled with the `collective_setup` namelist flag.

----

I think this was meant to be included in Zhi's commit: 521dbf6095eb17a25b2e8a73423704c4d0b688fa

I have turned on the collectives by default, but I can disable them if that would be safer.

### CODE REVIEW

**Comment by underwoo** [comment]
Thank you for the pull request.  We will look at this, and decide if this is something we will include in our internal release.  If we do, we will push that up to github.

**Comment by marshallward** [comment]
This is something that Zhi had already looked into, so you may want to ask
him about it.

**Comment by underwoo** [comment]
I have passed this on to Zhi to look into.

Thank you again for the update.

--
Seth Underwood
Engility

Modeling Systems Group
GFDL/NOAA/DOC
201 Forrestal Road
Princeton, NJ 08540-6649

(609) 452-5847 Office
(304) 376-9002 Cell
(609) 987-5063 Fax
Seth.Underwood@noaa.gov

**Comment by underwoo** [comment]
I got word back from @Zhi-Liang, and his update was done in commit 4a9e22b7f, and is now part of the dev/master branch --- and slated to be in the next release.  Please review his changes and let me know if they are sufficient.

**Comment by marshallward** [comment]
This looks fine, Zhi's changes look OK.  I got confused because only part
of it had been merged into master.

We might prefer the alltoallv to be enabled by default in the future, but
currently it is not necessary.

Do you have a release date in mind for this?  We'd like to modify the MOM5
repository to directly link to FMS at some point, but we currently cannot
run our 0.1 (cm2.6 based) model without these changes.

(Also feel free to close this issue)

**Pull request closed without merging**
