### PR TITLE
Include.file.extensions

### PR DESCRIPTION
**Pull request by underwoo**
**Description**
Example of what changes will be required to use the new Fortran file extension standards for libFMS.  The file extensions for Fortran include files are:

Extension | Description
-- | --
*.fh | Files that contain only Fortran `INTERFACE` or variable definitions, and do not need to be preprocessed
*.FH | Same as *.fh, but need to be preprocessed
*.inc | Files that contain more than just Fortran interface definitions (e.g. Fortran code, function, subroutines), and do not need to be preprocessed.
*.INC | Same as *.inc, but need to be preprocessed
*.h | C/C++ headers, or files that ONLY contain preprocessor macros that are safe to include in C/C++ and possibly Fortran

None of the Fortran include files should have `USE` statements, except for minimal use in *.inc or *.INC when within a `SUBROUTINE` or `FUNCTION`.  If a use statement is required, then a Fortran module should be created.  Placing `USE` statements outside of a Fortran routine in an include file restricts where the file can be included, and inhibits including multiple files that may have `USE` statements.

**How Has This Been Tested?**
Contains both autotools and CMake builds.  Autotools build is tested on Mac OS x, and via travis-ci.  The CMake build is still in development, and was run on Mac OS X.

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

### CODE REVIEW

**Comment by underwoo** [comment]
This branch in now up-to-date with the master branch.  There are still a few files that use `#include <file>` with files that reside in the repository.  I'll get those updated soon.

**Comment by thomas-robinson** [comment]
@underwoo Do you think this will be ready for 2020.02?

**Comment by underwoo** [comment]
> @underwoo Do you think this will be ready for 2020.02?

I should be.  Only a few more updates are needed (in the tests), and then merge in the nest updates.

**Comment by underwoo** [comment]
This needs to be updated.  Closing for now.

**Pull request closed without merging**
